"""empty message

Revision ID: 3996314f3c27
Revises: 14137fec37ba
Create Date: 2018-03-02 19:22:18.163273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3996314f3c27'
down_revision = '14137fec37ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'password')
    # ### end Alembic commands ###
